### ISSUE TITLE
 Build and release changelog if tagged - download/upload changelog failing

### ISSUE THREAD

**Issue by dotherightthing** [dotherightthing/wpdtrt-npm-scripts#67]
This line appears to be failing: `if: steps.check-tag.outputs.match == 'true'`

**Comment by dotherightthing** [comment]
Try <https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow> to separate build and release workflows, plus:

```yml
  on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
```
