### ISSUE TITLE
Cypress - chown: cannot access '/home/runner/.cache': No such file or directory

### ISSUE THREAD

**Issue by dotherightthing** [dotherightthing/wpdtrt-npm-scripts#70]
See <https://github.com/dotherightthing/wpdtrt-plugin-boilerplate/actions/runs/3218085266/jobs/5261818641>

**Comment by dotherightthing** [comment]
Do the steps need to be reversed?

```yml
    # Fix Cypress cannot write to the cache directory due to file permissions
    # https://github.com/cypress-io/cypress/issues/1281
    # TODO chown: cannot access '/home/runner/.cache': No such file or directory
    # - name: Grant Cypress permission to download to cache directory
    #   run: |
    #     sudo chown $USER $HOME/.cache
    
    # https://github.com/cypress-io/github-action#install-cypress-only
    - name: Cache dependencies
      uses: actions/cache@v3
      id: cache
      with:
        path: |
          ~/.cache
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
```
